version: "3.9"

services:
  printer-api:
    build: .
    container_name: printer-api
    ports:
      - "9191:8000"
    restart: unless-stopped
    # Uncomment and adjust if you later add env vars
    # environment:
    #   PRINTER_TEMPLATES_DIR: "/app/app/templates"
